version: '3.8'  # Обновите версию до актуальной

services:
  app:
    container_name: app
    build: .
    restart: no
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: main.py
          target: /app/main.py
    environment:
      DATABASE_URL: postgresql://mephi:mephi@db/mephi-db
      
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mephi
      POSTGRES_PASSWORD: mephi
      POSTGRES_DB: mephi-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: pgadmin2
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: mephi@localhost.ru
      PGADMIN_DEFAULT_PASSWORD: mephi
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  pgdata:
  pgadmin:


